CREATE TABLE IF NOT EXISTS BOOK_PROJECTION (
    BOOK_ID TEXT NOT NULL,
    PROFILE TEXT NOT NULL,
    FILE_SIZE INTEGER NOT NULL,
    CREATED_DATE TEXT NOT NULL,
    LAST_MODIFIED_DATE TEXT NOT NULL,
    PRIMARY KEY (BOOK_ID, PROFILE)
);
